import type {Metadata} from "next";
import HeroInner from "@/components/hero-inner/heroInner";

export default function About() {
    return (
        <>
            <HeroInner title={'Über uns'}/>
        </>
    )
}

export const metadata: Metadata = {
    title: "About Page Example",
    description: "Generated by create next app and me",
};