import type {Metadata} from "next";
import HeroInner from "@/components/hero-inner/heroInner";
import Header from "@/components/header";
import Footer from "@/components/footer";

export default function About() {
    return (
        <>
            <Header/>
            <HeroInner title={'Über uns'}/>
            <Footer/>
        </>
    )
}

export const metadata: Metadata = {
    title: "About Page Example",
    description: "Generated by create next app and me",
};